### ISSUE TITLE
[Backend] Improve performance with multicore

### ISSUE THREAD

**Issue by giongto35** [giongto35/gowog#1]
Currently, the game gets the best performance when it runs with only one core.
With multi-cores, the performance slowed down due to concurrency.

**Comment by jjhesk** [comment]
i see the game is very laggy now and its not playable. it has 200mc latency..

**Comment by giongto35** [comment]
@jjhesk the latency is due to the location. The hosting is now in Singapore and US. Sorry I don't have much budget to spread the game servers.
It is smooth in South East Asia.
